//
// Created by 200458668 on 10/29/2021.
//

#ifndef SFMLTEST_DEFINITIONS_HPP
#define SFMLTEST_DEFINITIONS_HPP


#define SCREEN_WIDTH 768
#define SCREEN_HEIGHT 1136
#define SPLASH_STATE_DISPLAY_TIME .5
#define SPLACH_SCENE_BACKGROUND_FILE_PATH "Resources/Splash_Background.png"

#endif//SFMLTEST_DEFINITIONS_HPP
